"""CLI plumbing: read TrendingResult JSON, write DraftBundle JSON.

Unix-style stage — reads from stdin (or `--input path`), writes to stdout
(or `--output path`). Composes as:

    trend-radar-cli | python -m writer | renderer

Skips suppressed topics (trend-radar marks these when the novelty ledger
matches a prior story). Use `--include-suppressed` to override.
"""
from __future__ import annotations

import argparse
import asyncio
import json
import sys
from pathlib import Path

from writer.agent import DEFAULT_MODEL, build_agent, write_draft
from writer.models import DraftBundle, TrendingResultIn


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        prog="pipeline-writer",
        description="Turn trend-radar TrendingResult JSON into DraftBundle JSON.",
    )
    p.add_argument(
        "--input", "-i", type=Path, default=None,
        help="Path to TrendingResult JSON. Default: read from stdin.",
    )
    p.add_argument(
        "--output", "-o", type=Path, default=None,
        help="Path to write DraftBundle JSON. Default: write to stdout.",
    )
    p.add_argument(
        "--limit", "-n", type=int, default=None,
        help="Only write drafts for the top-N topics. Default: all non-suppressed.",
    )
    p.add_argument(
        "--include-suppressed", action="store_true",
        help="Include topics marked suppressed by the novelty gate.",
    )
    p.add_argument(
        "--model", default=DEFAULT_MODEL,
        help=f"Pydantic AI model string. Default: {DEFAULT_MODEL} (env WRITER_MODEL).",
    )
    p.add_argument(
        "--dry-run", action="store_true",
        help="Skip the LLM. Emit stub drafts (echo topic + rationale, no prose).",
    )
    return p.parse_args(argv)


def _read_input(path: Path | None) -> TrendingResultIn:
    text = path.read_text() if path else sys.stdin.read()
    return TrendingResultIn.model_validate_json(text)


def _write_output(bundle: DraftBundle, path: Path | None) -> None:
    payload = bundle.model_dump_json(indent=2)
    if path:
        path.write_text(payload)
    else:
        sys.stdout.write(payload + "\n")


def _stub_draft(rt):  # type: ignore[no-untyped-def]
    """Dry-run placeholder — no LLM call, deterministic output for pipeline wiring tests."""
    from writer.models import Draft, DraftSource
    return Draft(
        topic_id=rt.topic_id,
        canonical_title=rt.topic.canonical_title,
        headline=rt.topic.canonical_title[:100] or "Untitled",
        subhead=rt.topic.one_line[:200] or "No one-liner",
        body_md="[dry-run] Draft body would be generated by the LLM here.",
        key_signals=[
            f"final_score={rt.score.final_score:.3f}",
            f"distinct_sources={rt.distinct_sources}",
        ],
        sources=[
            DraftSource(
                title=si.item.title,
                url=si.item.url,
                source=si.item.source,
                signal=f"raw_score={si.item.raw_score:.0f}",
            )
            for si in rt.items[:3]
        ] or [DraftSource(
            title=rt.topic.canonical_title, url="https://example.invalid",
            source="hackernews", signal="no items in cluster",
        )],
        ranking_rationale=rt.score.explanation,
    )


async def _run(args: argparse.Namespace) -> int:
    trending = _read_input(args.input)

    topics = [t for t in trending.topics if args.include_suppressed or not t.suppressed]
    if args.limit is not None:
        topics = topics[: args.limit]

    if not topics:
        print("writer: no topics to draft (all suppressed?)", file=sys.stderr)
        _write_output(
            DraftBundle(run_id=trending.run_id, generated_at=trending.generated_at, drafts=[]),
            args.output,
        )
        return 0

    if args.dry_run:
        drafts = [_stub_draft(t) for t in topics]
    else:
        agent = build_agent(args.model)
        drafts = []
        for i, t in enumerate(topics, 1):
            print(f"writer: drafting {i}/{len(topics)} — {t.topic.canonical_title}", file=sys.stderr)
            drafts.append(await write_draft(t, agent=agent))

    _write_output(
        DraftBundle(run_id=trending.run_id, generated_at=trending.generated_at, drafts=drafts),
        args.output,
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    return asyncio.run(_run(args))


if __name__ == "__main__":
    sys.exit(main())
